### PR TITLE
CI code that produces the confusion matrix from episode 2 on 3 operating systems

### LINKED ISSUE #233: Create CI job to reproduce confusion matrix
As we produce a confusion matrix in episode 3, we ran into reproduction issues during class. For the sake of sanity, it might be very helpful to create a CI job that

- [x] instantiates all dependencies for a fixed python version across all 3 OSes
- [ ] runs all cells of episode 3 using a fixed seed
- [x] stores/prints the confusion matrix obtained

### PR DESCRIPTION
**Pull request by psteinb**
This closes #233

### CODE REVIEW

**Comment by psteinb** [comment]
This PR pulls in the `cce` app into the repo. I needed to fix a small bug in it and thought then I could include it straight away.

**Comment by psteinb** [comment]
Open question for me: should I try to find a way to either:
- create CI artifacts (the confusion matrices in a `.txt` file)
- or try to commit back the confusion matrix into the repo in any way.
Feedback welcome.

**Comment by dafnevk** [comment]
> This PR pulls in the `cce` app into the repo. I needed to fix a small bug in it and thought then I could include it straight away.

Maybe this is fine for now, the cce tool does not have an actual release and is not very actively maintained. However, we may develop and maintain it further in the `esciencecenter-digital-skills` organization, then we don't want to maintain a copy.

**Comment by dafnevk** [comment]
Would your idea be to include the output of this action directly into the lesson material? Then I guess we need to
1. add a (hidden) line of code into the episode that writes a `.png`  file
2. Have the CI commit the image back

Of course we can only include the output for one run one one OS in the final lesson.

**Comment by svenvanderburg** [comment]
Closing this PR as it is stale for over a year now.

**Pull request closed without merging**
