### PR TITLE
summarizing the design considerations for this material

### PR DESCRIPTION
**Pull request by psteinb**
Design motivation and ideas from #49

### CODE REVIEW

**Comment by psteinb** [comment]
I copied the text from #49 as is for now. I would consider a subsequent PR with concrete hints down the road once this is merged.

**Comment by psteinb** [comment]
the unit tests fail with an error for me on travis even though.

```
$ make lesson-check-all

Ignoring executable-hooks-1.6.0 because its extensions are not built. Try: gem pristine executable-hooks --version 1.6.0

Ignoring gem-wrappers-1.4.0 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.4.0

Traceback (most recent call last):

	2: from bin/markdown_ast.rb:5:in `<main>'

	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'

/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- kramdown (LoadError)

Traceback (most recent call last):

  File "bin/lesson_check.py", line 569, in <module>

    main()

  File "bin/lesson_check.py", line 122, in main

    docs = read_all_markdown(args.source_dir, args.parser)

  File "bin/lesson_check.py", line 266, in read_all_markdown

    data = read_markdown(parser, filename)

  File "/home/travis/build/psteinb/deep-learning-intro/bin/util.py", line 122, in read_markdown

    doc = json.loads(stdout_data)

  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads

    return _default_decoder.decode(s)

  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Makefile:139: recipe for target 'lesson-check-all' failed

make: *** [lesson-check-all] Error 1
```

**Comment by tobyhodges** [comment]
Indeed the lesson template is moving over to GitHub Actions away from Travis and I should sync those changes to the Incubator template too. This PR has also made me realise that the Incubator template needs an `_includes/links.md` file as well.

**Comment by psteinb** [comment]
@tobyhodges thanks for the confirmation, that I didn't oversee anything. Note `links.md` depends on `_includes/base_path.html` from what I could tell.

**Pull request merged**
